FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["CNA261 Project.csproj", "./"]
RUN dotnet restore "CNA261 Project.csproj"

COPY . .
RUN dotnet publish "CNA261 Project.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "/app/CNA261 Project.dll"]
